/* Copyright (C) 2024 Eccelerators GmbH
   
   This code was generated by:
  
   HxS Compiler 1.0.20-9104d5ff
   C Extension for HxS 1.0.25-33698831
   
   Further information at https://eccelerators.com/hxs
   
   Changes to this file may cause incorrect behavior and will be lost if the
   code is regenerated.
*/	
	
#ifndef _LedIfc_H
#define _LedIfc_H

/* ----------------------------------------------------- */
/* Addresses, widths, values and masks for direct access */
/* ----------------------------------------------------- */
#define LedIfcAddressBusWidth 4
#define LedIfcDataBusWidth 32

#define LedBlkAddress 0x0
#define LedBlkSize 0x4

#define CtrRegAddress (0x0 + LedBlkAddress)
#define CtrRegWidth 32

#define OnOffMask 0x00000001
#define OnOffPosition 0
#define OnOffWidth 1
#define LedOffMVal 0x00000000
#define LedOnMVal 0x00000001
#define OnOffBusResetMRstVal 0x00000000

#endif